// ═══════════════════════════════════════
//  SHARED COCKTAIL DATA — 50 Recipes
//  Used by both main page and bar scanner
// ═══════════════════════════════════════
const cocktails = [
  // ── חזק ומר ──
  {name:"Negroni",category:"strong",desc:"שילוש מושלם של מרירות, מתיקות ובוטניקה.",difficulty:"easy",sweet:3,sour:1,complex:6,
    ingredients:[{item:"ג'ין",amount:"30 מ\"ל"},{item:"קמפרי",amount:"30 מ\"ל"},{item:"ורמוט מתוק",amount:"30 מ\"ל"}],
    steps:["יוצקים את כל המרכיבים לכוס ערבוב עם קרח","מערבבים כ-30 שניות","מסננים לכוס רוקס על קוביית קרח גדולה","מקשטים בקליפת תפוז"]},
  {name:"Old Fashioned",category:"strong",desc:"אבן הפינה של תרבות הקוקטיילים — פשוט, חזק, נצחי.",difficulty:"easy",sweet:3,sour:0,complex:5,
    ingredients:[{item:"בורבון",amount:"60 מ\"ל"},{item:"קוביית סוכר",amount:"1"},{item:"אנגוסטורה ביטרס",amount:"2-3 דשים"}],
    steps:["מניחים קוביית סוכר בכוס רוקס","מוסיפים ביטרס ומועכים בעדינות","מוסיפים קרח גדול ובורבון","מערבבים בעדינות ומקשטים בקליפת תפוז"]},
  {name:"Manhattan",category:"strong",desc:"אלגנטיות ניו יורקית בכל לגימה.",difficulty:"easy",sweet:4,sour:0,complex:6,
    ingredients:[{item:"וויסקי ריי",amount:"60 מ\"ל"},{item:"ורמוט מתוק",amount:"30 מ\"ל"},{item:"אנגוסטורה ביטרס",amount:"2 דשים"}],
    steps:["יוצקים את כל המרכיבים לכוס ערבוב עם קרח","מערבבים כ-30 שניות","מסננים לכוס מרטיני מצוננת","מקשטים בדובדבן מרסקינו"]},
  {name:"Sazerac",category:"strong",desc:"הקוקטייל הוותיק ביותר מניו אורלינס.",difficulty:"hard",sweet:2,sour:0,complex:8,
    ingredients:[{item:"וויסקי ריי",amount:"60 מ\"ל"},{item:"אבסינת (שטיפה)",amount:"דש"},{item:"ביטרס פישו",amount:"3 דשים"},{item:"קוביית סוכר",amount:"1"}],
    steps:["שוטפים כוס רוקס מצוננת באבסינת ומשליכים","בכוס נפרדת מועכים סוכר עם ביטרס","מוסיפים ריי וקרח, מערבבים היטב","מסננים לכוס המצופה, מקשטים בקליפת לימון"]},
  {name:"Boulevardier",category:"strong",desc:"נגרוני עם בורבון — חם יותר, עמוק יותר.",difficulty:"easy",sweet:3,sour:1,complex:6,
    ingredients:[{item:"בורבון",amount:"45 מ\"ל"},{item:"קמפרי",amount:"30 מ\"ל"},{item:"ורמוט מתוק",amount:"30 מ\"ל"}],
    steps:["יוצקים את כל המרכיבים לכוס ערבוב עם קרח","מערבבים 30 שניות","מסננים לכוס רוקס על קרח","מקשטים בטוויסט תפוז"]},
  {name:"Rob Roy",category:"strong",desc:"מנהטן סקוטי — עשן פוגש מתיקות.",difficulty:"easy",sweet:4,sour:0,complex:5,
    ingredients:[{item:"סקוטש",amount:"60 מ\"ל"},{item:"ורמוט מתוק",amount:"30 מ\"ל"},{item:"אנגוסטורה ביטרס",amount:"2 דשים"}],
    steps:["יוצקים את כל המרכיבים לכוס ערבוב עם קרח","מערבבים 30 שניות","מסננים לכוס מרטיני","מקשטים בדובדבן מרסקינו"]},
  {name:"Vieux Carré",category:"strong",desc:"מורכבות צרפתית-אמריקאית בכוס אחת.",difficulty:"hard",sweet:4,sour:0,complex:9,
    ingredients:[{item:"וויסקי ריי",amount:"30 מ\"ל"},{item:"קוניאק",amount:"30 מ\"ל"},{item:"ורמוט מתוק",amount:"30 מ\"ל"},{item:"בנדיקטין",amount:"10 מ\"ל"},{item:"ביטרס",amount:"2 דשים"}],
    steps:["יוצקים את כל המרכיבים לכוס ערבוב עם קרח","מערבבים היטב 30 שניות","מסננים לכוס רוקס על קוביית קרח גדולה","מקשטים בקליפת לימון"]},
  {name:"Black Russian",category:"strong",desc:"פשטות מוחלטת — וודקה וקפה.",difficulty:"easy",sweet:5,sour:0,complex:3,
    ingredients:[{item:"וודקה",amount:"50 מ\"ל"},{item:"קהלואה",amount:"25 מ\"ל"}],
    steps:["ממלאים כוס רוקס בקרח","יוצקים וודקה וקהלואה","מערבבים בעדינות"]},
  {name:"Americano",category:"strong",desc:"אפריטיבו איטלקי קלאסי, מרענן ומר.",difficulty:"easy",sweet:3,sour:1,complex:4,
    ingredients:[{item:"קמפרי",amount:"30 מ\"ל"},{item:"ורמוט מתוק",amount:"30 מ\"ל"},{item:"סודה",amount:"למילוי"}],
    steps:["ממלאים כוס הייבול בקרח","יוצקים קמפרי וורמוט","ממלאים בסודה ומערבבים בעדינות","מקשטים בפרוסת תפוז"]},
  {name:"Toronto",category:"strong",desc:"אולד פאשנד עם פרנט ברנקה — מר ומורכב.",difficulty:"medium",sweet:2,sour:0,complex:7,
    ingredients:[{item:"וויסקי ריי",amount:"60 מ\"ל"},{item:"פרנט ברנקה",amount:"15 מ\"ל"},{item:"סירופ פשוט",amount:"5 מ\"ל"},{item:"ביטרס",amount:"2 דשים"}],
    steps:["יוצקים את כל המרכיבים לכוס ערבוב עם קרח","מערבבים 30 שניות","מסננים לכוס רוקס על קרח","מקשטים בקליפת תפוז"]},
  {name:"Oaxacan Old Fashioned",category:"strong",desc:"טוויסט מקסיקני מעושן על הקלאסיקה.",difficulty:"medium",sweet:3,sour:0,complex:7,
    ingredients:[{item:"טקילה",amount:"45 מ\"ל"},{item:"מזקל",amount:"15 מ\"ל"},{item:"סירופ אגבה",amount:"10 מ\"ל"},{item:"ביטרס מולה",amount:"2 דשים"}],
    steps:["יוצקים את כל המרכיבים לכוס ערבוב עם קרח","מערבבים 30 שניות","מסננים לכוס רוקס על קרח גדול","מקשטים בקליפת תפוז מלוהטת"]},
  {name:"Negroni Sbagliato",category:"strong",desc:"הנגרוני ה'טעות' — פרוסקו במקום ג'ין.",difficulty:"easy",sweet:4,sour:1,complex:5,
    ingredients:[{item:"קמפרי",amount:"30 מ\"ל"},{item:"ורמוט מתוק",amount:"30 מ\"ל"},{item:"פרוסקו",amount:"30 מ\"ל"}],
    steps:["ממלאים כוס יין בקרח","יוצקים קמפרי וורמוט","ממלאים בפרוסקו","מערבבים בעדינות ומקשטים בפרוסת תפוז"]},
  {name:"Paper Plane",category:"strong",desc:"רביעייה מאוזנת לחלוטין בחלקים שווים.",difficulty:"medium",sweet:3,sour:4,complex:7,
    ingredients:[{item:"בורבון",amount:"22 מ\"ל"},{item:"אפרול",amount:"22 מ\"ל"},{item:"אמרו נונינו",amount:"22 מ\"ל"},{item:"מיץ לימון",amount:"22 מ\"ל"}],
    steps:["יוצקים את כל המרכיבים לשייקר עם קרח","מנערים בחוזקה 15 שניות","מסננים סינון כפול לכוס קופה","מגישים ללא קישוט"]},
  {name:"Last Word",category:"strong",desc:"קלאסיקה נשכחת שחזרה בגדול.",difficulty:"medium",sweet:3,sour:4,complex:8,
    ingredients:[{item:"ג'ין",amount:"22 מ\"ל"},{item:"שארטרוז ירוק",amount:"22 מ\"ל"},{item:"ליקר מרסקינו",amount:"22 מ\"ל"},{item:"מיץ ליים",amount:"22 מ\"ל"}],
    steps:["יוצקים את כל המרכיבים לשייקר עם קרח","מנערים בחוזקה","מסננים סינון כפול לכוס קופה","מקשטים בדובדבן מרסקינו"]},
  {name:"Jungle Bird",category:"strong",desc:"טרופי פוגש מר — שילוב מנצח ובלתי צפוי.",difficulty:"medium",sweet:4,sour:3,complex:6,
    ingredients:[{item:"רום כהה",amount:"45 מ\"ל"},{item:"קמפרי",amount:"22 מ\"ל"},{item:"מיץ אננס",amount:"45 מ\"ל"},{item:"מיץ ליים",amount:"15 מ\"ל"}],
    steps:["יוצקים את כל המרכיבים לשייקר עם קרח","מנערים בחוזקה","מסננים לכוס רוקס על קרח","מקשטים בפרוסת אננס"]},

  // ── מתוק וקרמי ──
  {name:"White Russian",category:"sweet",desc:"האח הקרמי של הרוסי השחור.",difficulty:"easy",sweet:7,sour:0,complex:3,
    ingredients:[{item:"וודקה",amount:"50 מ\"ל"},{item:"קהלואה",amount:"25 מ\"ל"},{item:"שמנת מתוקה",amount:"25 מ\"ל"}],
    steps:["ממלאים כוס רוקס בקרח","יוצקים וודקה וקהלואה","מציפים שמנת בעדינות על גב כפית"]},
  {name:"Brandy Alexander",category:"sweet",desc:"אלגנטיות של תור הזהב, עשיר וקרמי.",difficulty:"easy",sweet:8,sour:0,complex:4,
    ingredients:[{item:"קוניאק",amount:"30 מ\"ל"},{item:"קרם דה קקאו לבן",amount:"30 מ\"ל"},{item:"שמנת מתוקה",amount:"30 מ\"ל"}],
    steps:["יוצקים את כל המרכיבים לשייקר עם קרח","מנערים בחוזקה","מסננים לכוס קופה","מפזרים אגוז מוסקט טרי"]},
  {name:"Mudslide",category:"sweet",desc:"קינוח נוזלי שאי אפשר לעמוד בפניו.",difficulty:"easy",sweet:9,sour:0,complex:2,
    ingredients:[{item:"וודקה",amount:"30 מ\"ל"},{item:"קהלואה",amount:"30 מ\"ל"},{item:"בייליס",amount:"30 מ\"ל"}],
    steps:["יוצקים את כל המרכיבים לשייקר עם קרח","מנערים בחוזקה","מסננים לכוס רוקס על קרח","מקשטים בשוקולד מגורר"]},
  {name:"Grasshopper",category:"sweet",desc:"ירוק, מנטה, קרמי — קינוח בכוס.",difficulty:"easy",sweet:8,sour:0,complex:2,
    ingredients:[{item:"קרם דה מנט ירוק",amount:"30 מ\"ל"},{item:"קרם דה קקאו לבן",amount:"30 מ\"ל"},{item:"שמנת מתוקה",amount:"30 מ\"ל"}],
    steps:["יוצקים את כל המרכיבים לשייקר עם קרח","מנערים בחוזקה","מסננים לכוס מרטיני מצוננת","מקשטים בעלה נענע"]},
  {name:"Chocolate Martini",category:"sweet",desc:"פינוק שוקולד אלגנטי.",difficulty:"easy",sweet:8,sour:0,complex:3,
    ingredients:[{item:"וודקה",amount:"45 מ\"ל"},{item:"ליקר שוקולד",amount:"30 מ\"ל"},{item:"שמנת",amount:"15 מ\"ל"}],
    steps:["יוצקים את כל המרכיבים לשייקר עם קרח","מנערים בחוזקה","מסננים לכוס מרטיני","מקשטים בשבבי שוקולד"]},
  {name:"Golden Cadillac",category:"sweet",desc:"קלאסיקה אמריקאית עשירה עם נגיעות וניל.",difficulty:"easy",sweet:7,sour:0,complex:4,
    ingredients:[{item:"גליאנו",amount:"30 מ\"ל"},{item:"קרם דה קקאו לבן",amount:"30 מ\"ל"},{item:"שמנת מתוקה",amount:"30 מ\"ל"}],
    steps:["יוצקים את כל המרכיבים לשייקר עם קרח","מנערים בחוזקה","מסננים לכוס קופה מצוננת"]},
  {name:"Pink Squirrel",category:"sweet",desc:"ורוד, אגוזי, קרמי — רטרו במיטבו.",difficulty:"easy",sweet:8,sour:0,complex:3,
    ingredients:[{item:"קרם דה נויו",amount:"30 מ\"ל"},{item:"קרם דה קקאו לבן",amount:"30 מ\"ל"},{item:"שמנת מתוקה",amount:"30 מ\"ל"}],
    steps:["יוצקים את כל המרכיבים לשייקר עם קרח","מנערים בחוזקה","מסננים לכוס מרטיני מצוננת"]},
  {name:"Toasted Almond",category:"sweet",desc:"שקדים קלויים בכוס — חלומי.",difficulty:"easy",sweet:7,sour:0,complex:3,
    ingredients:[{item:"אמרטו",amount:"30 מ\"ל"},{item:"קהלואה",amount:"30 מ\"ל"},{item:"שמנת מתוקה",amount:"30 מ\"ל"}],
    steps:["ממלאים כוס רוקס בקרח","יוצקים אמרטו וקהלואה","מציפים שמנת על גב כפית"]},
  {name:"Bushwacker",category:"sweet",desc:"פינה קולדה פוגשת קפה קר — פיצוץ טרופי-קרמי.",difficulty:"medium",sweet:9,sour:0,complex:4,
    ingredients:[{item:"רום",amount:"30 מ\"ל"},{item:"קהלואה",amount:"30 מ\"ל"},{item:"בייליס",amount:"30 מ\"ל"},{item:"קרם קוקוס",amount:"30 מ\"ל"},{item:"גלידת וניל",amount:"כדור 1"}],
    steps:["מערבבים את כל המרכיבים בבלנדר","מוסיפים קרח ומערבבים עד לטקסטורה חלקה","יוצקים לכוס הוריקן","מקשטים בקוקוס מגורר ושוקולד"]},
  {name:"Baileys Colada",category:"sweet",desc:"פינה קולדה אירית — שמנת פוגשת טרופי.",difficulty:"easy",sweet:8,sour:0,complex:3,
    ingredients:[{item:"בייליס",amount:"45 מ\"ל"},{item:"רום",amount:"30 מ\"ל"},{item:"קרם קוקוס",amount:"30 מ\"ל"},{item:"מיץ אננס",amount:"60 מ\"ל"}],
    steps:["מערבבים את כל המרכיבים עם קרח בבלנדר","מערבבים עד לטקסטורה חלקה","יוצקים לכוס הוריקן","מקשטים בפרוסת אננס"]},
  {name:"Carajillo",category:"sweet",desc:"ליקר 43 ואספרסו — פשטות ספרדית מושלמת.",difficulty:"easy",sweet:6,sour:0,complex:4,
    ingredients:[{item:"ליקר 43",amount:"45 מ\"ל"},{item:"אספרסו כפול",amount:"שוט 1"},{item:"קרח",amount:"כוס מלאה"}],
    steps:["ממלאים כוס רוקס בקרח","יוצקים ליקר 43","מוסיפים אספרסו כפול חם ישירות על הקרח","מערבבים בעדינות"]},

  // ── חמוץ ומרענן ──
  {name:"Margarita",category:"sour",desc:"מלכת הקוקטיילים החמוצים — תמיד קלאסית.",difficulty:"easy",sweet:3,sour:7,complex:4,
    ingredients:[{item:"טקילה",amount:"50 מ\"ל"},{item:"מיץ ליים",amount:"25 מ\"ל"},{item:"טריפל סק",amount:"20 מ\"ל"}],
    steps:["יוצקים את כל המרכיבים לשייקר עם קרח","מנערים בחוזקה","מסננים לכוס מרגריטה עם שפת מלח","מקשטים בפלח ליים"]},
  {name:"Daiquiri",category:"sour",desc:"שלושה מרכיבים, אלף אפשרויות.",difficulty:"easy",sweet:3,sour:6,complex:3,
    ingredients:[{item:"רום לבן",amount:"60 מ\"ל"},{item:"מיץ ליים טרי",amount:"25 מ\"ל"},{item:"סירופ פשוט",amount:"15 מ\"ל"}],
    steps:["יוצקים את כל המרכיבים לשייקר עם קרח","מנערים בחוזקה 15 שניות","מסננים סינון כפול לכוס קופה מצוננת","מקשטים בגלגל ליים"]},
  {name:"Whiskey Sour",category:"sour",desc:"בורבון עם קצף משי — שלמות.",difficulty:"medium",sweet:3,sour:6,complex:5,
    ingredients:[{item:"בורבון",amount:"60 מ\"ל"},{item:"מיץ לימון",amount:"25 מ\"ל"},{item:"סירופ פשוט",amount:"20 מ\"ל"},{item:"חלבון ביצה",amount:"1"}],
    steps:["מנערים את כל המרכיבים ללא קרח 15 שניות","מוסיפים קרח ומנערים שוב בחוזקה","מסננים סינון כפול לכוס רוקס","מקשטים בטיפות ביטרס על הקצף"]},
  {name:"Mojito",category:"sour",desc:"הקיץ הקובני בכוס אחת.",difficulty:"easy",sweet:4,sour:5,complex:3,
    ingredients:[{item:"רום לבן",amount:"50 מ\"ל"},{item:"מיץ ליים",amount:"25 מ\"ל"},{item:"סירופ פשוט",amount:"20 מ\"ל"},{item:"נענע טרייה",amount:"8-10 עלים"},{item:"סודה",amount:"למילוי"}],
    steps:["מועכים בעדינות עלי נענע עם סירופ וליים","ממלאים את הכוס בקרח כתוש","יוצקים רום ומערבבים","ממלאים בסודה ומקשטים בנענע"]},
  {name:"Tom Collins",category:"sour",desc:"קלאסיקה בריטית מרעננת.",difficulty:"easy",sweet:3,sour:5,complex:3,
    ingredients:[{item:"ג'ין",amount:"50 מ\"ל"},{item:"מיץ לימון",amount:"25 מ\"ל"},{item:"סירופ פשוט",amount:"15 מ\"ל"},{item:"סודה",amount:"למילוי"}],
    steps:["יוצקים ג'ין, לימון וסירופ לשייקר עם קרח","מנערים בחוזקה","מסננים לכוס הייבול על קרח","ממלאים בסודה, מקשטים בלימון ודובדבן"]},
  {name:"Gimlet",category:"sour",desc:"פשטות בריטית — ג'ין וליים, נקודה.",difficulty:"easy",sweet:3,sour:6,complex:3,
    ingredients:[{item:"ג'ין",amount:"60 מ\"ל"},{item:"מיץ ליים טרי",amount:"22 מ\"ל"},{item:"סירופ פשוט",amount:"15 מ\"ל"}],
    steps:["יוצקים את כל המרכיבים לשייקר עם קרח","מנערים בחוזקה","מסננים סינון כפול לכוס קופה","מקשטים בגלגל ליים"]},
  {name:"French 75",category:"sour",desc:"ג'ין ושמפניה — חגיגה צרפתית.",difficulty:"medium",sweet:3,sour:5,complex:5,
    ingredients:[{item:"ג'ין",amount:"30 מ\"ל"},{item:"מיץ לימון",amount:"15 מ\"ל"},{item:"סירופ פשוט",amount:"10 מ\"ל"},{item:"שמפניה",amount:"60 מ\"ל"}],
    steps:["יוצקים ג'ין, לימון וסירופ לשייקר עם קרח","מנערים בחוזקה","מסננים לכוס שמפניה","ממלאים בשמפניה קרה"]},
  {name:"Bee's Knees",category:"sour",desc:"ג'ין ודבש — מתקופת היובש.",difficulty:"easy",sweet:4,sour:5,complex:4,
    ingredients:[{item:"ג'ין",amount:"60 מ\"ל"},{item:"מיץ לימון",amount:"22 מ\"ל"},{item:"סירופ דבש",amount:"22 מ\"ל"}],
    steps:["יוצקים את כל המרכיבים לשייקר עם קרח","מנערים בחוזקה","מסננים סינון כפול לכוס קופה","מקשטים בטוויסט לימון"]},
  {name:"Clover Club",category:"sour",desc:"ורוד, חמוץ, קצפי — אלגנטיות נשכחת שחזרה לחיים.",difficulty:"medium",sweet:4,sour:5,complex:5,
    ingredients:[{item:"ג'ין",amount:"45 מ\"ל"},{item:"מיץ לימון",amount:"22 מ\"ל"},{item:"סירופ פטל",amount:"22 מ\"ל"},{item:"חלבון ביצה",amount:"1"}],
    steps:["מנערים את כל המרכיבים ללא קרח","מוסיפים קרח ומנערים שוב בחוזקה","מסננים סינון כפול לכוס קופה","מקשטים בפטל טרי"]},
  {name:"Penicillin",category:"sour",desc:"התרופה הסקוטית המושלמת.",difficulty:"medium",sweet:3,sour:5,complex:7,
    ingredients:[{item:"סקוטש בלנדד",amount:"50 מ\"ל"},{item:"סקוטש איילה (ציפה)",amount:"10 מ\"ל"},{item:"מיץ לימון",amount:"22 מ\"ל"},{item:"סירופ ג'ינג'ר-דבש",amount:"22 מ\"ל"}],
    steps:["יוצקים סקוטש בלנדד, לימון וסירופ לשייקר עם קרח","מנערים בחוזקה","מסננים סינון כפול לכוס רוקס על קרח","מציפים סקוטש איילה מעל"]},
  {name:"Amaretto Sour",category:"sour",desc:"חמוץ-מתוק עם עומק של בורבון.",difficulty:"medium",sweet:5,sour:5,complex:4,
    ingredients:[{item:"אמרטו",amount:"45 מ\"ל"},{item:"בורבון",amount:"22 מ\"ל"},{item:"מיץ לימון",amount:"30 מ\"ל"},{item:"סירופ פשוט",amount:"10 מ\"ל"},{item:"חלבון ביצה",amount:"1"}],
    steps:["מנערים את כל המרכיבים ללא קרח","מוסיפים קרח ומנערים שוב בחוזקה","מסננים סינון כפול לכוס רוקס על קרח","מקשטים בדובדבן וביטרס על הקצף"]},

  // ── פירותי וטרופי ──
  {name:"Espresso Martini",category:"fruity",desc:"אנרגיה ואלגנטיות בכוס אחת.",difficulty:"medium",sweet:4,sour:1,complex:5,
    ingredients:[{item:"וודקה",amount:"45 מ\"ל"},{item:"קהלואה",amount:"22 מ\"ל"},{item:"אספרסו טרי",amount:"שוט 1"},{item:"סירופ פשוט",amount:"10 מ\"ל"}],
    steps:["יוצקים את כל המרכיבים לשייקר עם קרח","מנערים בחוזקה 15 שניות ליצירת קרמה","מסננים סינון כפול לכוס מרטיני מצוננת","מקשטים ב-3 פולי קפה"]},
  {name:"Aperol Spritz",category:"fruity",desc:"שקיעה איטלקית בכוס — קיץ בלגימה.",difficulty:"easy",sweet:5,sour:2,complex:3,
    ingredients:[{item:"פרוסקו",amount:"90 מ\"ל"},{item:"אפרול",amount:"60 מ\"ל"},{item:"סודה",amount:"30 מ\"ל"}],
    steps:["ממלאים כוס יין גדולה בקרח","יוצקים פרוסקו ואפרול","ממלאים בסודה","מערבבים בעדינות ומקשטים בפרוסת תפוז"]},
  {name:"Pina Colada",category:"fruity",desc:"חוף טרופי בכל לגימה.",difficulty:"easy",sweet:7,sour:1,complex:2,
    ingredients:[{item:"רום לבן",amount:"60 מ\"ל"},{item:"קרם קוקוס",amount:"45 מ\"ל"},{item:"מיץ אננס",amount:"90 מ\"ל"}],
    steps:["מערבבים את כל המרכיבים עם קרח בבלנדר","מערבבים עד לטקסטורה חלקה","יוצקים לכוס הוריקן","מקשטים באננס ודובדבן"]},
  {name:"Mai Tai",category:"fruity",desc:"מלך הטיקי — רום, שקד וליים.",difficulty:"hard",sweet:4,sour:4,complex:7,
    ingredients:[{item:"רום לבן",amount:"30 מ\"ל"},{item:"רום כהה",amount:"30 מ\"ל"},{item:"טריפל סק",amount:"15 מ\"ל"},{item:"סירופ אורגט",amount:"15 מ\"ל"},{item:"מיץ ליים",amount:"25 מ\"ל"}],
    steps:["יוצקים את כל המרכיבים לשייקר עם קרח","מנערים בחוזקה","מסננים לכוס רוקס על קרח כתוש","מקשטים בענף נענע ופלח ליים"]},
  {name:"Pornstar Martini",category:"fruity",desc:"פסיפלורה, וניל ושמפניה — להיט העשור.",difficulty:"medium",sweet:6,sour:3,complex:5,
    ingredients:[{item:"וודקה וניל",amount:"45 מ\"ל"},{item:"ליקר פסיפלורה",amount:"15 מ\"ל"},{item:"מיץ פסיפלורה",amount:"30 מ\"ל"},{item:"מיץ ליים",amount:"15 מ\"ל"}],
    steps:["יוצקים את כל המרכיבים לשייקר עם קרח","מנערים בחוזקה","מסננים סינון כפול לכוס קופה","מקשטים בחצי פסיפלורה, מגישים עם שוט פרוסקו בצד"]},
  {name:"Paloma",category:"fruity",desc:"האלטרנטיבה המקסיקנית האמיתית למרגריטה.",difficulty:"easy",sweet:3,sour:4,complex:3,
    ingredients:[{item:"טקילה",amount:"50 מ\"ל"},{item:"מיץ ליים",amount:"15 מ\"ל"},{item:"מיץ אשכולית",amount:"45 מ\"ל"},{item:"סודה אשכולית",amount:"למילוי"}],
    steps:["ממלאים כוס הייבול בקרח","יוצקים טקילה, ליים ומיץ אשכולית","ממלאים בסודה אשכולית","מערבבים ומקשטים בפרוסת אשכולית"]},
  {name:"Cosmopolitan",category:"fruity",desc:"ורוד, אלגנטי, ותמיד רלוונטי.",difficulty:"easy",sweet:4,sour:4,complex:4,
    ingredients:[{item:"וודקה הדרים",amount:"40 מ\"ל"},{item:"טריפל סק",amount:"15 מ\"ל"},{item:"מיץ ליים",amount:"15 מ\"ל"},{item:"מיץ חמוציות",amount:"30 מ\"ל"}],
    steps:["יוצקים את כל המרכיבים לשייקר עם קרח","מנערים בחוזקה","מסננים סינון כפול לכוס מרטיני מצוננת","מקשטים בטוויסט תפוז מלוהט"]},
  {name:"Sex on the Beach",category:"fruity",desc:"פירותי, מתוק, ואי אפשר להפסיק לשתות.",difficulty:"easy",sweet:7,sour:2,complex:2,
    ingredients:[{item:"וודקה",amount:"40 מ\"ל"},{item:"שנפס אפרסק",amount:"20 מ\"ל"},{item:"מיץ תפוזים",amount:"40 מ\"ל"},{item:"מיץ חמוציות",amount:"40 מ\"ל"}],
    steps:["ממלאים כוס הייבול בקרח","יוצקים את כל המרכיבים","מערבבים בעדינות","מקשטים בפרוסת תפוז"]},
  {name:"Tequila Sunrise",category:"fruity",desc:"זריחה בכוס — שכבות של צבע וטעם.",difficulty:"easy",sweet:6,sour:2,complex:2,
    ingredients:[{item:"טקילה",amount:"45 מ\"ל"},{item:"מיץ תפוזים",amount:"120 מ\"ל"},{item:"גרנדין",amount:"15 מ\"ל"}],
    steps:["ממלאים כוס הייבול בקרח","יוצקים טקילה ומיץ תפוזים","מערבבים בעדינות","יוצקים גרנדין לאט בצד הכוס"]},
  {name:"Singapore Sling",category:"fruity",desc:"מסע טרופי מורכב מהמזרח הרחוק.",difficulty:"hard",sweet:5,sour:3,complex:8,
    ingredients:[{item:"ג'ין",amount:"30 מ\"ל"},{item:"ליקר דובדבן",amount:"15 מ\"ל"},{item:"בנדיקטין",amount:"7 מ\"ל"},{item:"קוואנטרו",amount:"7 מ\"ל"},{item:"מיץ ליים",amount:"15 מ\"ל"},{item:"מיץ אננס",amount:"60 מ\"ל"},{item:"גרנדין",amount:"10 מ\"ל"},{item:"ביטרס",amount:"דש 1"}],
    steps:["יוצקים את כל המרכיבים לשייקר עם קרח","מנערים בחוזקה","מסננים לכוס הייבול על קרח","מקשטים באננס ודובדבן"]},
  {name:"Hurricane",category:"fruity",desc:"סופה טרופית מניו אורלינס.",difficulty:"easy",sweet:7,sour:3,complex:4,
    ingredients:[{item:"רום לבן",amount:"30 מ\"ל"},{item:"רום כהה",amount:"30 מ\"ל"},{item:"מיץ פסיפלורה",amount:"60 מ\"ל"},{item:"מיץ תפוזים",amount:"30 מ\"ל"},{item:"מיץ ליים",amount:"15 מ\"ל"},{item:"גרנדין",amount:"15 מ\"ל"}],
    steps:["יוצקים את כל המרכיבים לשייקר עם קרח","מנערים בחוזקה","מסננים לכוס הוריקן על קרח","מקשטים בפרוסת תפוז ודובדבן"]},
  {name:"Lemon Drop",category:"fruity",desc:"חמוץ-מתוק מושלם עם שפת סוכר.",difficulty:"easy",sweet:5,sour:6,complex:3,
    ingredients:[{item:"וודקה לימון",amount:"45 מ\"ל"},{item:"מיץ לימון",amount:"22 מ\"ל"},{item:"סירופ פשוט",amount:"15 מ\"ל"}],
    steps:["מכינים שפת סוכר על כוס מרטיני","יוצקים את כל המרכיבים לשייקר עם קרח","מנערים בחוזקה","מסננים סינון כפול לכוס, מקשטים בגלגל לימון"]},
  {name:"Blue Lagoon",category:"fruity",desc:"כחול חשמלי — מראה שלא שוכחים.",difficulty:"easy",sweet:6,sour:3,complex:2,
    ingredients:[{item:"וודקה",amount:"45 מ\"ל"},{item:"בלו קוראסאו",amount:"22 מ\"ל"},{item:"לימונדה",amount:"למילוי"}],
    steps:["ממלאים כוס הייבול בקרח","יוצקים וודקה ובלו קוראסאו","ממלאים בלימונדה","מערבבים ומקשטים בפרוסת לימון"]}
];

// ═══════════════════════════════════════
//  CATEGORY META
// ═══════════════════════════════════════
const categories = {
  strong: { name: "חזק ומר", count: 15 },
  sweet:  { name: "מתוק וקרמי", count: 11 },
  sour:   { name: "חמוץ ומרענן", count: 11 },
  fruity: { name: "פירותי וטרופי", count: 13 }
};

// ═══════════════════════════════════════
//  IMAGE CACHE — TheCocktailDB API
// ═══════════════════════════════════════
// All 50 cocktail images — hardcoded for instant loading and correct matching
const cocktailImages = {
  "Negroni":"https://www.thecocktaildb.com/images/media/drink/qgdu971561574065.jpg",
  "Old Fashioned":"https://www.thecocktaildb.com/images/media/drink/vrwquq1478252802.jpg",
  "Manhattan":"https://www.thecocktaildb.com/images/media/drink/yk70e31606771240.jpg",
  "Sazerac":"https://www.thecocktaildb.com/images/media/drink/vvpxwy1439907208.jpg",
  "Boulevardier":"https://www.thecocktaildb.com/images/media/drink/km84qi1513705868.jpg",
  "Rob Roy":"https://www.thecocktaildb.com/images/media/drink/typuyq1439456976.jpg",
  "Vieux Carré":"https://www.thecocktaildb.com/images/media/drink/b522ek1521761610.jpg",
  "Black Russian":"https://www.thecocktaildb.com/images/media/drink/8oxlqf1606772765.jpg",
  "Americano":"https://www.thecocktaildb.com/images/media/drink/709s6m1613655124.jpg",
  "Toronto":"https://www.thecocktaildb.com/images/media/drink/yqsvtw1478252982.jpg",
  "Oaxacan Old Fashioned":"https://www.thecocktaildb.com/images/media/drink/vrwquq1478252802.jpg",
  "Negroni Sbagliato":"https://www.thecocktaildb.com/images/media/drink/j9evx11504373665.jpg",
  "Paper Plane":"https://www.thecocktaildb.com/images/media/drink/x72sik1606854964.jpg",
  "Last Word":"https://www.thecocktaildb.com/images/media/drink/91oule1513702624.jpg",
  "Jungle Bird":"https://www.thecocktaildb.com/images/media/drink/urpyqs1439907531.jpg",
  "White Russian":"https://www.thecocktaildb.com/images/media/drink/vsrupw1472405732.jpg",
  "Brandy Alexander":"https://www.thecocktaildb.com/images/media/drink/mlyk1i1606772340.jpg",
  "Mudslide":"https://www.thecocktaildb.com/images/media/drink/tpwwut1468925017.jpg",
  "Grasshopper":"https://www.thecocktaildb.com/images/media/drink/aqm9el1504369613.jpg",
  "Chocolate Martini":"https://www.thecocktaildb.com/images/media/drink/tpwwut1468925017.jpg",
  "Golden Cadillac":"https://www.thecocktaildb.com/images/media/drink/qrot6j1504369425.jpg",
  "Pink Squirrel":"https://www.thecocktaildb.com/images/media/drink/t0aja61504348715.jpg",
  "Toasted Almond":"https://www.thecocktaildb.com/images/media/drink/vr6kle1504886114.jpg",
  "Bushwacker":"https://www.thecocktaildb.com/images/media/drink/rvwrvv1468877323.jpg",
  "Baileys Colada":"https://www.thecocktaildb.com/images/media/drink/upgsue1668419912.jpg",
  "Carajillo":"https://www.thecocktaildb.com/images/media/drink/vqwptt1441247711.jpg",
  "Margarita":"https://www.thecocktaildb.com/images/media/drink/5noda61589575158.jpg",
  "Daiquiri":"https://www.thecocktaildb.com/images/media/drink/mrz9091589574515.jpg",
  "Whiskey Sour":"https://www.thecocktaildb.com/images/media/drink/hbkfsh1589574990.jpg",
  "Mojito":"https://www.thecocktaildb.com/images/media/drink/metwgh1606770327.jpg",
  "Tom Collins":"https://www.thecocktaildb.com/images/media/drink/7cll921606854636.jpg",
  "Gimlet":"https://www.thecocktaildb.com/images/media/drink/3xgldt1513707271.jpg",
  "French 75":"https://www.thecocktaildb.com/images/media/drink/hrxfbl1606773109.jpg",
  "Bee's Knees":"https://www.thecocktaildb.com/images/media/drink/3xgldt1513707271.jpg",
  "Clover Club":"https://www.thecocktaildb.com/images/media/drink/t0aja61504348715.jpg",
  "Penicillin":"https://www.thecocktaildb.com/images/media/drink/hc9b1a1521853096.jpg",
  "Amaretto Sour":"https://www.thecocktaildb.com/images/media/drink/xnzc541493070211.jpg",
  "Espresso Martini":"https://www.thecocktaildb.com/images/media/drink/n0sx531504372951.jpg",
  "Aperol Spritz":"https://www.thecocktaildb.com/images/media/drink/iloasq1587661955.jpg",
  "Pina Colada":"https://www.thecocktaildb.com/images/media/drink/upgsue1668419912.jpg",
  "Mai Tai":"https://www.thecocktaildb.com/images/media/drink/twyrrp1439907470.jpg",
  "Pornstar Martini":"https://www.thecocktaildb.com/images/media/drink/xjhjdf1630406071.jpg",
  "Paloma":"https://www.thecocktaildb.com/images/media/drink/samm5j1513706393.jpg",
  "Cosmopolitan":"https://www.thecocktaildb.com/images/media/drink/kpsajh1504368362.jpg",
  "Sex on the Beach":"https://www.thecocktaildb.com/images/media/drink/fi67641668420787.jpg",
  "Tequila Sunrise":"https://www.thecocktaildb.com/images/media/drink/quqyqp1480879103.jpg",
  "Singapore Sling":"https://www.thecocktaildb.com/images/media/drink/7dozeg1582578095.jpg",
  "Hurricane":"https://www.thecocktaildb.com/images/media/drink/nwx02s1515795822.jpg",
  "Lemon Drop":"https://www.thecocktaildb.com/images/media/drink/mtpxgk1504373297.jpg",
  "Blue Lagoon":"https://www.thecocktaildb.com/images/media/drink/5wm4zo1582579154.jpg"
};

// Category name mapping
const categoryNames = { strong: "חזק ומר", sweet: "מתוק וקרמי", sour: "חמוץ ומרענן", fruity: "פירותי וטרופי" };

